bot_dev/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^home/',include('trial_bot.urls')),
]

trial_bot/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
app_name="trial_bot"

urlpatterns = [
    url(r'^train/$', views.train,name='train'),
    url(r'^train/save/$', views.save_conv,name='save_conv'),
    url(r'^train/analyse/$', views.analyse,name='analyse')
    

]

trial_bot/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import redirect,reverse

# Create your models here.


class Chats(models.Model):
	que=models.CharField(max_length=500)
	pro_ans=models.CharField(max_length=500)
	sug_ans=models.CharField(max_length=500)
	name=models.CharField(max_length=50)


	def __str__(self):
		return self.name

	# def get_absolute_url(self):
	# 	return reverse('groups:join',kwargs={'pk':self.pk})

trial_bot/forms.py
from django import forms 

class train_form(forms.Form):
	que= forms.CharField(label='Question', max_length=500)

trial_bot/views.py
import json
from django.shortcuts import render
from . models import Chats
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.

def train(request):
	return render(request,'./train.html')

@csrf_exempt
def save_conv(request):
	chat=Chats()
	if request.method=='POST':
		print(request)
		req=json.loads(request.body)
		print(req)
		chat.que=req['que']
		chat.pro_ans=req['pro_ans']
		chat.sug_ans=req['sug_ans']
		if req['user']!="":
			chat.name=req['user']
		else:
			chat.name="anonymous"

		chat.save()

		print("success")
		return JsonResponse({
			'status': 'success',
			'msg': 'recieved the 3 things'
		})



def analyse(request):
	chat=Chats.objects.all()
	sug_chats=[]
	unsug_chats=[]
	for i in chat:
		if i.sug_ans=="":
			unsug_chats.append(i)
		else:
			sug_chats.append(i)

	if not request.POST._mutable:
   		request.POST._mutable = True

	context={'sug_chats':sug_chats,'unsug_chats':unsug_chats,'nsug_chats':len(sug_chats),'nunsug_chats':len(unsug_chats),
	'pnsug_chats':(len(unsug_chats)*100/len(chat)),'psug_chats':(len(sug_chats)*100/len(chat))
	}
	print(context)
	return render(request,"analyse.html",context)

templates/train.html
<!DOCTYPE html>
<html>

<head>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
	 crossorigin="anonymous">


	<title>Train Me</title>
</head>

<body>

	<div class="jumbotron">
		<form>
			<input type="text" name="que">
			<br> ans
			<br>

			<input type="submit" name="Ask" class="btn btn-primary">
			<br>
			<input type="text" name="suggested_ans">
			<br>
			<input type="submit" name="submit" class="btn btn-primary">
			<br>
		</form>
	</div>

</body>

</html>

trial_bot/templates/analyse.html
<!DOCTYPE html>
<html>

<head>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
	 crossorigin="anonymous">
    

    <title>Train Me</title>
    <style>
            td {margin: auto}
            tr {margin: auto}
            </style>
</head>

<body>

	<div class="jumbotron">
		<h2> Welcome to Chatbot Analysis Center, Avartan 2018</h2>
</div>

<div style="color:white;background-color:red; height:50px ;width :{{psug_chats}}%;">Suggestions : {{nsug_chats}}</div>
<br>
<div style="color:white;background-color:steelblue; height:50px ;width :{{pnsug_chats}}%;">Satisfactory Replies : {{nunsug_chats}}</div>
<br><br>
<div style="border:2px solid grey;width:50%;float:left;"><center>Satisfactory Replies</center>
    <table>
    <tr><td>Question</td><td>Answer</td></tr>
    {% for i in unsug_chats %}
    <tr><td>{{i.que}}</td><td>{{i.pro_ans}}</td></tr>
    {% endfor%}
    </table>
</div>

<div style="border:2px solid grey;width:50%;float:right;"> <center>Unsatisfactory Replies</center>
    <table>
    <tr><td>Question</td><td>Bot Answer</td><td>Suggetsed Answer</td></tr>
    {% for i in sug_chats %}
    <tr><td>{{i.que}}</td><td>{{i.pro_ans}}</td><td>{{i.sug_ans}}</td></tr>
{% endfor%}
</table>
</div>
Instructions : Write the question in the box provided; an answer will be displayed.
If you are not satisfied by the answer write your name and suggestion and press submit again.

</div>

</body>
</html>

trial_bot/templates/train.html
<!DOCTYPE html>
<html>

<head>

	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
	 crossorigin="anonymous">


	<title>Train Me</title>
</head>

<body>

	<div class="jumbotron">
		<h2> Welcome to Chatbot Training Ground, Avartan 2018</h2>

		<div class="container">
			<br>
			<br>
			<form action="{% url 'trial_bot:save_conv' %}" method="post">

				{% csrf_token %}
				<label for="que">Question</label>
				<input type="text" name="que" id="que">
				<input type="submit" name="submit" class="btn btn-primary" id='submit_btn'>
				<br> <br>Answer :
				<span id="ans"></span>
				<br>

				<br> Not Satisfied by the answer, Suggest here :-
				<br><br>
				<label for="sug_ans">Suggestion</label>
				<input type="text" name="sug_ans" value="" id="id1"><br>
				<label for="user">Name</label>
				<input type="text" name="user" id="user">
				<br>
			</form>
		</div>
	</div>




	<script>

		var btn = document.querySelector('#submit_btn')

		btn.addEventListener('click', e => {
			e.preventDefault()
			

			$.ajax({
				type: 'POST',
				url: 'http://adarshshrivastava001.pythonanywhere.com/bot/',
				data: {
					'que': document.getElementById("que").value
				},
				dataType: 'json',
				success: function (data) {
					console.log(data)
					document.getElementById("ans").innerHTML = data.ans;

					save_locally()
				}
			})
		})

		save_locally = () => {
			fetch('/home/train/save/', {
				method: 'post',
				body: JSON.stringify({
					'que': document.getElementById("que").value,
					'pro_ans': document.getElementById('ans').innerHTML,
					'sug_ans': document.querySelector('[name=sug_ans]').value,
					'user': document.querySelector('[name=user]').value
				})
			})  

				
				
				.then(d => d.json())
				.then(d => {
					console.log(d)
				})
				.catch(err => console.error(err))

				document.querySelector('[name=sug_ans]').value=""
		}


	</script>


	<script src="//cdn.jsdelivr.net/npm/medium-editor@5.23.2/dist/js/medium-editor.min.js"></script>


	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
	 crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	 crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
	 crossorigin="anonymous"></script>

	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

</body>

</html>